//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAccountApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookdbEntities : DbContext
    {
        public bookdbEntities()
            : base("name=bookdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countriesCodes> countriesCodes { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<durationsTable> durationsTable { get; set; }
        public virtual DbSet<error> error { get; set; }
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<flightTable> flightTable { get; set; }
        public virtual DbSet<fromTable> fromTable { get; set; }
        public virtual DbSet<office> office { get; set; }
        public virtual DbSet<operations> operations { get; set; }
        public virtual DbSet<passengers> passengers { get; set; }
        public virtual DbSet<payOp> payOp { get; set; }
        public virtual DbSet<serviceData> serviceData { get; set; }
        public virtual DbSet<setting> setting { get; set; }
        public virtual DbSet<setValues> setValues { get; set; }
        public virtual DbSet<statementsTable> statementsTable { get; set; }
        public virtual DbSet<toTable> toTable { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<userSetValues> userSetValues { get; set; }
        public virtual DbSet<officeFiles> officeFiles { get; set; }
        public virtual DbSet<passengerFiles> passengerFiles { get; set; }
        public virtual DbSet<serviceDataFiles> serviceDataFiles { get; set; }
        public virtual DbSet<paySides> paySides { get; set; }
    }
}
