//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAccountApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class officeSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public officeSystem()
        {
            this.serviceData = new HashSet<serviceData>();
        }
    
        public int osId { get; set; }
        public Nullable<int> officeId { get; set; }
        public Nullable<int> systemId { get; set; }
        public Nullable<decimal> office_commission { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string notes { get; set; }
    
        public virtual office office { get; set; }
        public virtual systems systems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceData> serviceData { get; set; }
    }
}
