//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAccountApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetails
    {
        public int id { get; set; }
        public string activateCode { get; set; }
        public Nullable<int> isCurrent { get; set; }
        public string state { get; set; }
    }
}
